### ISSUE TITLE
Read word2vec in Pyhton 2.7

### ISSUE THREAD

**Issue by anavaldi** [Kyubyong/wordvectors#15]
How can I read the word2vec files in Python 2.7?

**Comment by brun0xff** [comment]
check this link https://radimrehurek.com/gensim/models/word2vec.html

**Comment by anavaldi** [comment]
I mean how can I read the word2vec files of the language files: https://drive.google.com/file/d/0B0ZXk88koS2KYkd5OVExR3o1V1k/view

**Comment by anavaldi** [comment]
path = 'data\ca.bin'
word_vectors = KeyedVectors.load(path)
