### ISSUE TITLE
Missing numpy objects for Portuguese

### ISSUE THREAD

**Issue by perone** [Kyubyong/wordvectors#2]
When loading the `pt.bin` on Gensim, it shows the error:

    [Errno 2] No such file or directory: 'pt.bin.syn1neg.npy'

Because the file `pt.bin.syn1neg.npy` is missing, does anyone who trained it has the file available ?

**Comment by Kyubyong** [comment]
Thanks, perone!

I forgot to include npy files. I've updated the linked file. Now download the zip file and try again. It should work.

**Comment by perone** [comment]
Fixed, great thanks @Kyubyong, it is working fine now.
