### ISSUE TITLE
Encoding Type for Pretrained Models

### ISSUE THREAD

**Issue by jlmeo** [Kyubyong/wordvectors#8]
What is the encoding type for the pre-trained word2vec models? When trying to load a pre-trained model file I get the following error, and I have not been successful in troubleshooting this.

(using Portuguese as an example here)

```
model = gensim.models.KeyedVectors.load_word2vec_format(
   'pt/pt.bin,
    binary=True,
)

```

Error message:
`UnicodeDecodeError: 'utf8' codec can't decode byte 0x93 in position 0: invalid start byte
`

**Comment by jlmeo** [comment]
The correct way to load one of these pretrained models is as follows:

`model = gensim.models.KeyedVectors.load( 'pt/pt.bin')`

**Comment by gitlost-murali** [comment]
And how do I get the vector of a particular word from the model. @jlmeo
